spring:
  profiles:
    active: test
  redis:
    host: 172.20.54.234
    password: F7+zm34cS91zsvA+8yLl
    port: 6381

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url:
        suite: jdbc:mysql://172.20.54.82:5001/esn_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: esn_open
      password: wglZQIwuIBbByV2QPloL
      min-idle: 2
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      max-active: 500
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      min-evictable-idle-time-millis: 300000
      max-wait: 60000
esn:
  inapi:
    salt: 5e0cb0fdf04aadbfad31df5ef5c8ded6
    agent_id: openapi
    host: http://in.api.chaoke.com:6062
    version: 1.0
    token: 25af978faf19020ad7dcdcedf6537062
  approvecenter:
    host: http://ys.chaoke.com:91/approvecenter
    authtoken: 44f3c13d-59f6-4ac6-b9ab-387d7734c2a1

management:
  endpoints:
    web:
      exposure:
       include: "*"  # * 在yaml 文件属于关键字，所以需要加引号
# diwork sdk ak
access:
  key: Vq4Es3CnrCu3wyRz
  secret: hsOpCEfKwmodk2mFFj7IPDMxbif07G

# diwork 开放平台加签
opendiwork:
  accesscenter_sign_url: https://developer.yonyoucloud.com/accesscenter/api/v1/access/signkey
  accesskey: nHry0uCYss9j7LYq
  userid_field: huishanguserid
  tenantid_field: tenantId

# 用友集团组织过滤
yonyou:
  tenant_id: qyic8c7o
  org_id: ab756309feca4c708af760ca14b34a91

#spring:
#  profiles:
#    active: daily
#  redis:
#    host: 172.20.53.43
#    password: F7+zm34cS91zsvA+8yLl
#    port: 6381
#
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      url:
#        suite: jdbc:mysql://172.20.53.185:5001/esn_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#      username: esn_open
#      password: wglZQIwuIBbByV2QPloL
#      min-idle: 2
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      max-active: 500
#      validation-query: SELECT 1 FROM DUAL
#      pool-prepared-statements: true
#      min-evictable-idle-time-millis: 300000
#      max-wait: 60000
#
#esn:
#  inapi:
#    salt: 5e0cb0fdf04aadbfad31df5ef5c8ded6
#    agent_id: openapi
#    host: https://in-api.yyuap.com
#    version: 1.0
#    token: 25af978faf19020ad7dcdcedf6537062
#  approvecenter:
#    host: http://ys.chaoke.com:91/approvecenter
#    authtoken: 44f3c13d-59f6-4ac6-b9ab-387d7734c2a1
#
#access:
#  key: Vq4Es3CnrCu3wyRz
#  secret: hsOpCEfKwmodk2mFFj7IPDMxbif07G
#
#opendiwork:
#  accesscenter_sign_url: https://developer.yonyoucloud.com/accesscenter/api/v1/access/signkey
#  accesskey: nHry0uCYss9j7LYq
#  userid_field: huishanguserid
#  tenantid_field: tenantId
#
## 用友集团组织过滤
#yonyou:
#  tenant_id: qyic8c7o
#  org_id: ab756309feca4c708af760ca14b34a91
